"""Business limits shared by parsers, services, and the desktop bridge."""

APP_NAME = "NEXUS DNA Retrieval Engine"
REFERENCE_LENGTH_MIN = 2_000
REFERENCE_LENGTH_MAX = 5_000
READ_COUNT = 50
READ_LENGTH_MIN = 50
READ_LENGTH_MAX = 150
K_MIN = 4
K_MAX = 12
DEFAULT_K = 6
MISMATCH_MIN = 0
MISMATCH_MAX = 4
DEFAULT_MISMATCHES = 2
PROTECTED_PREFIX_LENGTH = K_MAX
